name: tables_repository
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  formz: ^0.4.0
  intl: ^0.17.0
  syncfusion_flutter_datagrid: ^20.3.48
  http: ^0.13.5
  firebase_core: ^1.3.0
  cloud_firestore: ^2.3.0
  firebase_database: ^7.1.1
  firebase_auth: ^3.4.0
dev_dependencies:
