name: messager_repository
description: A new Flutter project. Creating a Flutter Firebase Chat application with provider state management.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  cloud_firestore: ^3.1.8
  firebase_storage: ^10.2.7
  google_sign_in: ^5.2.4
  fluttertoast: ^8.0.8
  image_picker: ^0.8.4+9
  shared_preferences: ^2.0.13
  intl: ^0.17.0
  photo_view: ^0.13.0
  provider: ^6.0.2
  country_code_picker: ^2.0.2
  url_launcher: ^6.0.20
  equatable: ^2.0.3
  google_sign_in_web: ^0.10.0+5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
# To add assets to your application, add an assets section, like this:
assets:
  - assets/images/
