// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEMCuUTyioXOhMRQA03THyXQhioIGW_Dw',
    appId: '1:872594570581:android:63dee598bac247680f03dc',
    messagingSenderId: '872594570581',
    projectId: 'mirea-course-work',
    storageBucket: 'mirea-course-work.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAalGDu_EoqNqyoFD0KsNDdBrYF8CWMwL0',
    appId: '1:872594570581:ios:4a6e736bc20c87510f03dc',
    messagingSenderId: '872594570581',
    projectId: 'mirea-course-work',
    storageBucket: 'mirea-course-work.appspot.com',
    iosClientId: '872594570581-pn1n8dq0mo3uthajpn93tigi66reqk6u.apps.googleusercontent.com',
    iosBundleId: 'com.example.coursework',
  );
}
